version: '3.8'

services:
  spring-dockerized-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - h2database
      - nginx
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:dcbapp
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - springboot-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  spring-dockerized-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8082
    depends_on:
      - h2database
      - nginx
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:dcbapp
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - springboot-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  spring-dockerized-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8082
    depends_on:
      - h2database
      - nginx
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:dcbapp
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - springboot-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  h2database:
    image: buildo/h2database
    ports:
      - 9092:9092
    networks:
      - springboot-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - springboot-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  springboot-network:
    name: springboot-network
    driver : bridge