
services:
  spring-dockerized-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - h2database
    networks:
      - springboot-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  spring-dockerized-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8082
    depends_on:
      - h2database
    networks:
      - springboot-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  spring-dockerized-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8082
    depends_on:
      - h2database
    networks:
      - springboot-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  h2database:
    image: buildo/h2database
    ports:
      - 9092:9092
    networks:
      - springboot-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - springboot-network
    depends_on:
      - spring-dockerized-app
      - spring-dockerized-app-2
      - spring-dockerized-app-3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  springboot-network:
    name: springboot-network
    driver : bridge